name: fcp-fdm

services:
  fcp-fdm-event-publisher-stub:
    ports:
      - '3002:3002'
    networks:
      - fcp-fdm

  floci:
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    volumes:
      - floci-data:/app/data
    networks:
      - fcp-fdm

  floci-init:
    networks:
      - fcp-fdm

networks:
  fcp-fdm:
    driver: bridge
    name: fcp-fdm

volumes:
  floci-data:
