services:
  fcp-fdm-event-publisher-stub:
    build:
      context: .
      target: development
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:fcp_event_publisher
      AWS_ENDPOINT_URL: http://localstack:4566
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  localstack:
    image: localstack/localstack
    environment:
      LS_LOG: warn
      SERVICES: sqs,sns
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
